### PR TITLE
Add database initialization on startup in docker-compose.yml

### PR DESCRIPTION
**Pull request by syenchuk**
Running `docker-compose up` as currently suggested in the README fails:

image

A database initialization (or migration) step needs to be performed before startup.

This pull request fixes this issue.

### CODE REVIEW

**Comment by syenchuk** [comment]
This also adds `.DS_Store` macOS system file to `.gitignore` and makes `./manage.py` executable which seems reasonable since it's the main entrypoint (and has a shebang, `#!/usr/bin/env python`).

**Comment by toxa23** [comment]
@alexpirine 
>A database initialization (or migration) step needs to be performed before startup.

Indeed, it should be performed. There is docker/sql/akihabara.sql which is supposed to be copied to /docker-entrypoint-initdb.d of Mysql container and executed on first startup. Could you please delete the container and its volume, run "docker-compose up" again and check for any errors in the output?

**Comment by syenchuk** [comment]
> docker/sql/akihabara.sql

Where is it? I don't see it on master branch.

**Comment by toxa23** [comment]
My bad :( Thank you for spotting the issue. Added missing files. Does it work now?

**Comment by syenchuk** [comment]
> My bad :( Thank you for spotting the issue. Added missing files. Does it work now?

I don't know, probably. Anyway wether it works or not doesn't matter. This is not an issue, this is a pull request.

**Comment by toxa23** [comment]
This .sql file contains an example database with users and content, whilst applying migrations on startup just create an empty DB. Me and @BanzaiTokyo prefer first way.

**Comment by syenchuk** [comment]
No worries, it's fine :)

I would rather use [fixtures](https://docs.djangoproject.com/en/3.1/howto/initial-data/) for this, but that's just personal preference.

**Pull request closed without merging**
